/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Do Tat Dat (https://sketchfab.com/dotatdat80)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dae-diorama-forest-loner-a0430ad032f6431ba4bc346acfe69903
Title: DAE Diorama - FOREST LONER
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Modale(props) {
  const { nodes, materials } = useGLTF("/dae_diorama_-_forest_loner.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[239.071, 160.908, 78.679]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.land002_grass_2_0.geometry}
            material={materials.grass_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.land002_grass_1_0.geometry}
            material={materials.grass_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.land002_soild_0.geometry}
            material={materials.soild}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mini_van_mini_van_0.geometry}
          material={materials.mini_van}
          position={[363.952, 360.298, -674.456]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trim_house_trim_wall_0.geometry}
          material={materials.trim_wall}
          position={[-268.935, 917.901, -602.732]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Camping_table_camnping_table_0.geometry}
          material={materials.camnping_table}
          position={[265.921, 278.608, 276.028]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vine_2_tree_vine_2_0.geometry}
          material={materials.tree_vine_2}
          position={[237.572, 354.568, -450.883]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.roof_1_roof_1_0.geometry}
          material={materials.roof_1}
          position={[-523.873, 882.828, -38.514]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.roof_2_roof_2_0.geometry}
          material={materials.roof_2}
          position={[-18.433, 1129.005, -972.528]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_wall_wood_wall_0.geometry}
          material={materials.wood_wall}
          position={[-495.955, 502.876, -3.416]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shed_shed_0.geometry}
          material={materials.shed}
          position={[26.736, 476.909, 285.23]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rock_wall_rock_wall_0.geometry}
          material={materials.rock_wall}
          position={[-476.848, 399.821, 196.699]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_pillar_wood_pilar_0.geometry}
          material={materials.wood_pilar}
          position={[79.494, 685.572, -586.078]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bridge_mesh_bridge_mesh_0.geometry}
          material={materials.bridge_mesh}
          position={[485.16, 867.644, -1023.547]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.river_river_surface_0.geometry}
          material={materials.river_surface}
          position={[1026.646, 100.517, 230.664]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass_4_Material_0.geometry}
          material={materials.Material}
          position={[78.653, 272.341, -2.019]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lunches_box_lunch_box_0.geometry}
          material={materials.lunch_box}
          position={[262.254, 297.693, 256.894]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.doors_windows_doors_windows_0.geometry}
          material={materials.doors_windows}
          position={[-147.739, 768.427, -386.9]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vine_1_vine_0.geometry}
          material={materials.vine}
          position={[-234.104, 500.38, 457.516]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rock_rock_0.geometry}
          material={materials.rock}
          position={[800.813, 155.853, 203.922]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.flowers_flower_0.geometry}
          material={materials.flower}
          position={[113.154, 317.389, 164.674]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.raven_animals_0.geometry}
          material={materials.animals}
          position={[258.256, 309.492, 305.985]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.food_food_0.geometry}
          material={materials.food}
          position={[252.254, 290.766, 300.835]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_floor_wood_floor_0.geometry}
          material={materials.wood_floor}
          position={[167.307, 581.266, -547.009]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pine_tree_leaf_pine_tree_leaf_0.geometry}
          material={materials.pine_tree_leaf}
          position={[-468.368, 895.083, 91.897]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pine_tree_bark_pine_tree_bark_0.geometry}
          material={materials.pine_tree_bark}
          position={[-320.778, 952.929, -72.722]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.remington_700_remington_700_0.geometry}
          material={materials.remington_700}
          position={[247.427, 274.937, 118.689]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bucket_bucket_0.geometry}
          material={materials.bucket}
          position={[272.948, 253.152, 654.477]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dog_animals_0.geometry}
          material={materials.animals}
          position={[238.68, 325.709, -259.415]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.squirrel_1_animals_0.geometry}
          material={materials.animals}
          position={[260.126, 286.897, -439.052]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.squirrel_2_animals_0.geometry}
          material={materials.animals}
          position={[-809.471, 1390.427, 68.328]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/dae_diorama_-_forest_loner.glb");
